---
formatter: markdown table

header-from: main.tf
content: |-
    # ☁️ AWS Secrets Manager
    ## Description
    {{ .Header }}

    This module simplifies the management of AWS Secrets Manager by creating a secret and integrating it with a Go application called "secret-manager-filler". The application is responsible for setting the actual value of the secret outside of Terraform, ensuring a secure and efficient secret handling process. The capabilities of this module correspond to the aws_secretsmanager_secret resource.
    A summary of its main features:

    🚀 Create a new AWS Secrets Manager secret.
    🚀 Seamlessly integrate with the "secret-manager-filler" Go application to set secret values outside Terraform.
    🚀 Utilize the aws_secretsmanager_secret resource for advanced secret management options.
    🚀 Enhance security and management of sensitive data in your AWS environment.

    ---
    ## Example
    Examples of this module's usage are available in the [examples](./examples) folder.

    ```hcl
    {{ include "../../examples/secrets-manager/basic/main.tf" }}
    ```


    Simple recipe:
    ```hcl
    {{ include "../../examples/secrets-manager/basic/config/fixtures.tfvars" }}
    ```

    Multiple secrets created, each with custom configurations.
    ```hcl
    {{ include "../../examples/secrets-manager/basic/config/fixtures-multiple.tfvars" }}
    ```
    Multiple secrets, some of them with enforced prefixes (for their paths)
    ```hcl
    {{ include "../../examples/secrets-manager/basic/config/fixtures-enforced-prefixes.tfvars" }}
    ```
    Secrets with replication enabled
    ```hcl
    {{ include "../../examples/secrets-manager/basic/config/fixtures-replication.tfvars" }}
    ```
    For module composition, It's recommended to take a look at the module's `outputs` to understand what's available:
    ```hcl
    {{ include "outputs.tf" }}
    ```
    ---

    ## Module's documentation
    (This documentation is auto-generated using [terraform-docs](https://terraform-docs.io))
    {{ .Providers }}

    {{ .Modules }}

    {{ .Resources }}

    {{ .Requirements }}

    {{ .Inputs }}

    {{ .Outputs }}

output:
    file: README.md
    mode: inject
    template: |-
        <!-- BEGIN_TF_DOCS -->
        {{ .Content }}
        <!-- END_TF_DOCS -->
settings:
    anchor: true
    color: true
