---
formatter: markdown table

header-from: main.tf
content: |-
    # ☁️ AWS Secrets Manager Rotation module
    ## Description
    {{ .Header }}

    This module sets IAM Policies, and optionally IAM roles attachments to specific roles in order to grant several permissions (E.g.: read a secret) to a specific service, or component.
    A summary of its main features:
    🚀 Create an IAM policy, based on a looked up AWS secret.
    🚀 Create optionally an attachment, if there's an IAM role that's passed.

    ---
    ## Example
    Examples of this module's usage are available in the [examples](./examples) folder.

    ```hcl
    {{ include "../../examples/secrets-manager-permissions/basic/main.tf" }}
    ```


    Simple recipe:
    ```hcl
    {{ include "../../examples/secrets-manager-permissions/basic/config/fixtures.tfvars" }}
    ```
    In this example, more elaborate permissions are granted
    ```hcl
    {{ include "../../examples/secrets-manager-permissions/basic/config/fixtures-permissions.tfvars" }}
    ```
    ---


    ## Module's documentation
    (This documentation is auto-generated using [terraform-docs](https://terraform-docs.io))
    {{ .Providers }}

    {{ .Modules }}

    {{ .Resources }}

    {{ .Requirements }}

    {{ .Inputs }}

    {{ .Outputs }}

output:
    file: README.md
    mode: inject
    template: |-
        <!-- BEGIN_TF_DOCS -->
        {{ .Content }}
        <!-- END_TF_DOCS -->
settings:
    anchor: true
    color: true
