---
formatter: markdown table

header-from: main.tf
content: |-
    # ☁️ AWS Secrets Manager Rotation module
    ## Description
    {{ .Header }}

    This module create the rotation configuration for a secret.
    A summary of its main features:
    🚀 Create the rotation configuration, with specific rules for the rotation lambda.
    🚀 Create the lambda permissions required for the lambda function to perform rotation actions on the target secret.
    🚀 Create an optional IAM (resource-based) policy that can be attached to the rotation lambda.

    It do not create the rotation lambda. It is up to you to create it, and to grant the proper permissions to the secret.

    ---
    ## Example
    Examples of this module's usage are available in the [examples](./examples) folder.

    ```hcl
    {{ include "../../examples/secrets-manager-rotation/basic/main.tf" }}
    ```

    Simple recipe:
    ```hcl
    {{ include "../../examples/secrets-manager-rotation/basic/config/fixtures.tfvars" }}
    ```

    In this example, a simple rotation configuration is required for a single (existing) secret
    ```hcl
    {{ include "../../examples/secrets-manager-rotation/basic/config/fixtures-rotation-simple.tfvars" }}
    ```

    In this example, multiple secret rotation configurations are passed.
    ```hcl
    {{ include "../../examples/secrets-manager-rotation/basic/config/fixtures-rotation-multiple.tfvars" }}
    ```

    ---

    ## Module's documentation
    (This documentation is auto-generated using [terraform-docs](https://terraform-docs.io))
    {{ .Providers }}

    {{ .Modules }}

    {{ .Resources }}

    {{ .Requirements }}

    {{ .Inputs }}

    {{ .Outputs }}

output:
    file: README.md
    mode: inject
    template: |-
        <!-- BEGIN_TF_DOCS -->
        {{ .Content }}
        <!-- END_TF_DOCS -->
settings:
    anchor: true
    color: true
